/PROG DRAW
/ATTR
OWNER		= MNEDITOR;
COMMENT		= "Portrait Drawing";
/MN
   1:   UFRAME_NUM=4;
   2:   UTOOL_NUM=9;
   3:  !Shape 1 ;
   4:L P[1] 200mm/sec CNT0 ;
   5:L P[2] 100mm/sec CNT0 ;
   6:L P[3] 50mm/sec CNT0 ;
   7:L P[4] 50mm/sec CNT0 ;
   8:L P[5] 50mm/sec CNT0 ;
   9:L P[6] 50mm/sec CNT0 ;
   10:L P[7] 50mm/sec CNT0 ;
   11:L P[8] 50mm/sec CNT0 ;
   12:L P[9] 50mm/sec CNT0 ;
   13:L P[10] 50mm/sec CNT0 ;
   14:L P[11] 50mm/sec CNT0 ;
   15:L P[12] 50mm/sec CNT0 ;
   16:L P[13] 50mm/sec CNT0 ;
   17:L P[14] 50mm/sec CNT0 ;
   18:L P[15] 50mm/sec CNT0 ;
   19:L P[16] 50mm/sec CNT0 ;
   20:L P[17] 50mm/sec CNT0 ;
   21:L P[18] 50mm/sec CNT0 ;
   22:L P[19] 100mm/sec CNT0 ;
   23:  !Shape 2 ;
   24:L P[20] 200mm/sec CNT0 ;
   25:L P[21] 100mm/sec CNT0 ;
   26:L P[22] 50mm/sec CNT0 ;
   27:L P[23] 50mm/sec CNT0 ;
   28:L P[24] 50mm/sec CNT0 ;
   29:L P[25] 50mm/sec CNT0 ;
   30:L P[26] 50mm/sec CNT0 ;
   31:L P[27] 50mm/sec CNT0 ;
   32:L P[28] 50mm/sec CNT0 ;
   33:L P[29] 50mm/sec CNT0 ;
   34:L P[30] 50mm/sec CNT0 ;
   35:L P[31] 50mm/sec CNT0 ;
   36:L P[32] 50mm/sec CNT0 ;
   37:L P[33] 50mm/sec CNT0 ;
   38:L P[34] 50mm/sec CNT0 ;
   39:L P[35] 50mm/sec CNT0 ;
   40:L P[36] 50mm/sec CNT0 ;
   41:L P[37] 50mm/sec CNT0 ;
   42:L P[38] 100mm/sec CNT0 ;
   43:  !Shape 3 ;
   44:L P[39] 200mm/sec CNT0 ;
   45:L P[40] 100mm/sec CNT0 ;
   46:L P[41] 50mm/sec CNT0 ;
   47:L P[42] 50mm/sec CNT0 ;
   48:L P[43] 50mm/sec CNT0 ;
   49:L P[44] 50mm/sec CNT0 ;
   50:L P[45] 50mm/sec CNT0 ;
   51:L P[46] 50mm/sec CNT0 ;
   52:L P[47] 50mm/sec CNT0 ;
   53:L P[48] 50mm/sec CNT0 ;
   54:L P[49] 50mm/sec CNT0 ;
   55:L P[50] 50mm/sec CNT0 ;
   56:L P[51] 50mm/sec CNT0 ;
   57:L P[52] 50mm/sec CNT0 ;
   58:L P[53] 50mm/sec CNT0 ;
   59:L P[54] 50mm/sec CNT0 ;
   60:L P[55] 50mm/sec CNT0 ;
   61:L P[56] 50mm/sec CNT0 ;
   62:L P[57] 50mm/sec CNT0 ;
   63:L P[58] 50mm/sec CNT0 ;
   64:L P[59] 50mm/sec CNT0 ;
   65:L P[60] 50mm/sec CNT0 ;
   66:L P[61] 50mm/sec CNT0 ;
   67:L P[62] 50mm/sec CNT0 ;
   68:L P[63] 50mm/sec CNT0 ;
   69:L P[64] 50mm/sec CNT0 ;
   70:L P[65] 50mm/sec CNT0 ;
   71:L P[66] 50mm/sec CNT0 ;
   72:L P[67] 50mm/sec CNT0 ;
   73:L P[68] 50mm/sec CNT0 ;
   74:L P[69] 50mm/sec CNT0 ;
   75:L P[70] 50mm/sec CNT0 ;
   76:L P[71] 50mm/sec CNT0 ;
   77:L P[72] 50mm/sec CNT0 ;
   78:L P[73] 50mm/sec CNT0 ;
   79:L P[74] 50mm/sec CNT0 ;
   80:L P[75] 50mm/sec CNT0 ;
   81:L P[76] 50mm/sec CNT0 ;
   82:L P[77] 50mm/sec CNT0 ;
   83:L P[78] 50mm/sec CNT0 ;
   84:L P[79] 50mm/sec CNT0 ;
   85:L P[80] 50mm/sec CNT0 ;
   86:L P[81] 50mm/sec CNT0 ;
   87:L P[82] 50mm/sec CNT0 ;
   88:L P[83] 50mm/sec CNT0 ;
   89:L P[84] 50mm/sec CNT0 ;
   90:L P[85] 50mm/sec CNT0 ;
   91:L P[86] 50mm/sec CNT0 ;
   92:L P[87] 50mm/sec CNT0 ;
   93:L P[88] 50mm/sec CNT0 ;
   94:L P[89] 50mm/sec CNT0 ;
   95:L P[90] 50mm/sec CNT0 ;
   96:L P[91] 50mm/sec CNT0 ;
   97:L P[92] 50mm/sec CNT0 ;
   98:L P[93] 100mm/sec CNT0 ;
   99:  !Shape 4 ;
   100:L P[94] 200mm/sec CNT0 ;
   101:L P[95] 100mm/sec CNT0 ;
   102:L P[96] 50mm/sec CNT0 ;
   103:L P[97] 50mm/sec CNT0 ;
   104:L P[98] 50mm/sec CNT0 ;
   105:L P[99] 50mm/sec CNT0 ;
   106:L P[100] 50mm/sec CNT0 ;
   107:L P[101] 50mm/sec CNT0 ;
   108:L P[102] 50mm/sec CNT0 ;
   109:L P[103] 50mm/sec CNT0 ;
   110:L P[104] 50mm/sec CNT0 ;
   111:L P[105] 50mm/sec CNT0 ;
   112:L P[106] 50mm/sec CNT0 ;
   113:L P[107] 50mm/sec CNT0 ;
   114:L P[108] 50mm/sec CNT0 ;
   115:L P[109] 50mm/sec CNT0 ;
   116:L P[110] 50mm/sec CNT0 ;
   117:L P[111] 50mm/sec CNT0 ;
   118:L P[112] 50mm/sec CNT0 ;
   119:L P[113] 50mm/sec CNT0 ;
   120:L P[114] 50mm/sec CNT0 ;
   121:L P[115] 50mm/sec CNT0 ;
   122:L P[116] 50mm/sec CNT0 ;
   123:L P[117] 50mm/sec CNT0 ;
   124:L P[118] 50mm/sec CNT0 ;
   125:L P[119] 50mm/sec CNT0 ;
   126:L P[120] 50mm/sec CNT0 ;
   127:L P[121] 50mm/sec CNT0 ;
   128:L P[122] 100mm/sec CNT0 ;
   129:  !Shape 5 ;
   130:L P[123] 200mm/sec CNT0 ;
   131:L P[124] 100mm/sec CNT0 ;
   132:L P[125] 50mm/sec CNT0 ;
   133:L P[126] 50mm/sec CNT0 ;
   134:L P[127] 50mm/sec CNT0 ;
   135:L P[128] 50mm/sec CNT0 ;
   136:L P[129] 50mm/sec CNT0 ;
   137:L P[130] 50mm/sec CNT0 ;
   138:L P[131] 50mm/sec CNT0 ;
   139:L P[132] 50mm/sec CNT0 ;
   140:L P[133] 50mm/sec CNT0 ;
   141:L P[134] 50mm/sec CNT0 ;
   142:L P[135] 50mm/sec CNT0 ;
   143:L P[136] 50mm/sec CNT0 ;
   144:L P[137] 50mm/sec CNT0 ;
   145:L P[138] 50mm/sec CNT0 ;
   146:L P[139] 50mm/sec CNT0 ;
   147:L P[140] 50mm/sec CNT0 ;
   148:L P[141] 50mm/sec CNT0 ;
   149:L P[142] 50mm/sec CNT0 ;
   150:L P[143] 50mm/sec CNT0 ;
   151:L P[144] 50mm/sec CNT0 ;
   152:L P[145] 50mm/sec CNT0 ;
   153:L P[146] 50mm/sec CNT0 ;
   154:L P[147] 50mm/sec CNT0 ;
   155:L P[148] 50mm/sec CNT0 ;
   156:L P[149] 100mm/sec CNT0 ;
   157:  !Shape 6 ;
   158:L P[150] 200mm/sec CNT0 ;
   159:L P[151] 100mm/sec CNT0 ;
   160:L P[152] 50mm/sec CNT0 ;
   161:L P[153] 50mm/sec CNT0 ;
   162:L P[154] 50mm/sec CNT0 ;
   163:L P[155] 50mm/sec CNT0 ;
   164:L P[156] 50mm/sec CNT0 ;
   165:L P[157] 50mm/sec CNT0 ;
   166:L P[158] 50mm/sec CNT0 ;
   167:L P[159] 50mm/sec CNT0 ;
   168:L P[160] 50mm/sec CNT0 ;
   169:L P[161] 50mm/sec CNT0 ;
   170:L P[162] 50mm/sec CNT0 ;
   171:L P[163] 50mm/sec CNT0 ;
   172:L P[164] 50mm/sec CNT0 ;
   173:L P[165] 50mm/sec CNT0 ;
   174:L P[166] 50mm/sec CNT0 ;
   175:L P[167] 50mm/sec CNT0 ;
   176:L P[168] 50mm/sec CNT0 ;
   177:L P[169] 50mm/sec CNT0 ;
   178:L P[170] 50mm/sec CNT0 ;
   179:L P[171] 50mm/sec CNT0 ;
   180:L P[172] 50mm/sec CNT0 ;
   181:L P[173] 50mm/sec CNT0 ;
   182:L P[174] 50mm/sec CNT0 ;
   183:L P[175] 50mm/sec CNT0 ;
   184:L P[176] 50mm/sec CNT0 ;
   185:L P[177] 50mm/sec CNT0 ;
   186:L P[178] 50mm/sec CNT0 ;
   187:L P[179] 50mm/sec CNT0 ;
   188:L P[180] 50mm/sec CNT0 ;
   189:L P[181] 50mm/sec CNT0 ;
   190:L P[182] 50mm/sec CNT0 ;
   191:L P[183] 50mm/sec CNT0 ;
   192:L P[184] 50mm/sec CNT0 ;
   193:L P[185] 50mm/sec CNT0 ;
   194:L P[186] 50mm/sec CNT0 ;
   195:L P[187] 50mm/sec CNT0 ;
   196:L P[188] 50mm/sec CNT0 ;
   197:L P[189] 50mm/sec CNT0 ;
   198:L P[190] 50mm/sec CNT0 ;
   199:L P[191] 50mm/sec CNT0 ;
   200:L P[192] 50mm/sec CNT0 ;
   201:L P[193] 50mm/sec CNT0 ;
   202:L P[194] 50mm/sec CNT0 ;
   203:L P[195] 50mm/sec CNT0 ;
   204:L P[196] 50mm/sec CNT0 ;
   205:L P[197] 50mm/sec CNT0 ;
   206:L P[198] 50mm/sec CNT0 ;
   207:L P[199] 50mm/sec CNT0 ;
   208:L P[200] 50mm/sec CNT0 ;
   209:L P[201] 50mm/sec CNT0 ;
   210:L P[202] 50mm/sec CNT0 ;
   211:L P[203] 50mm/sec CNT0 ;
   212:L P[204] 50mm/sec CNT0 ;
   213:L P[205] 50mm/sec CNT0 ;
   214:L P[206] 50mm/sec CNT0 ;
   215:L P[207] 50mm/sec CNT0 ;
   216:L P[208] 50mm/sec CNT0 ;
   217:L P[209] 50mm/sec CNT0 ;
   218:L P[210] 50mm/sec CNT0 ;
   219:L P[211] 50mm/sec CNT0 ;
   220:L P[212] 100mm/sec CNT0 ;
   221:  !Shape 7 ;
   222:L P[213] 200mm/sec CNT0 ;
   223:L P[214] 100mm/sec CNT0 ;
   224:L P[215] 50mm/sec CNT0 ;
   225:L P[216] 50mm/sec CNT0 ;
   226:L P[217] 50mm/sec CNT0 ;
   227:L P[218] 50mm/sec CNT0 ;
   228:L P[219] 50mm/sec CNT0 ;
   229:L P[220] 50mm/sec CNT0 ;
   230:L P[221] 50mm/sec CNT0 ;
   231:L P[222] 50mm/sec CNT0 ;
   232:L P[223] 50mm/sec CNT0 ;
   233:L P[224] 50mm/sec CNT0 ;
   234:L P[225] 50mm/sec CNT0 ;
   235:L P[226] 50mm/sec CNT0 ;
   236:L P[227] 50mm/sec CNT0 ;
   237:L P[228] 50mm/sec CNT0 ;
   238:L P[229] 50mm/sec CNT0 ;
   239:L P[230] 50mm/sec CNT0 ;
   240:L P[231] 50mm/sec CNT0 ;
   241:L P[232] 50mm/sec CNT0 ;
   242:L P[233] 50mm/sec CNT0 ;
   243:L P[234] 50mm/sec CNT0 ;
   244:L P[235] 50mm/sec CNT0 ;
   245:L P[236] 50mm/sec CNT0 ;
   246:L P[237] 50mm/sec CNT0 ;
   247:L P[238] 50mm/sec CNT0 ;
   248:L P[239] 50mm/sec CNT0 ;
   249:L P[240] 50mm/sec CNT0 ;
   250:L P[241] 50mm/sec CNT0 ;
   251:L P[242] 50mm/sec CNT0 ;
   252:L P[243] 50mm/sec CNT0 ;
   253:L P[244] 50mm/sec CNT0 ;
   254:L P[245] 50mm/sec CNT0 ;
   255:L P[246] 50mm/sec CNT0 ;
   256:L P[247] 50mm/sec CNT0 ;
   257:L P[248] 50mm/sec CNT0 ;
   258:L P[249] 50mm/sec CNT0 ;
   259:L P[250] 50mm/sec CNT0 ;
   260:L P[251] 50mm/sec CNT0 ;
   261:L P[252] 50mm/sec CNT0 ;
   262:L P[253] 50mm/sec CNT0 ;
   263:L P[254] 50mm/sec CNT0 ;
   264:L P[255] 50mm/sec CNT0 ;
   265:L P[256] 50mm/sec CNT0 ;
   266:L P[257] 50mm/sec CNT0 ;
   267:L P[258] 50mm/sec CNT0 ;
   268:L P[259] 50mm/sec CNT0 ;
   269:L P[260] 50mm/sec CNT0 ;
   270:L P[261] 50mm/sec CNT0 ;
   271:L P[262] 50mm/sec CNT0 ;
   272:L P[263] 50mm/sec CNT0 ;
   273:L P[264] 50mm/sec CNT0 ;
   274:L P[265] 50mm/sec CNT0 ;
   275:L P[266] 50mm/sec CNT0 ;
   276:L P[267] 50mm/sec CNT0 ;
   277:L P[268] 50mm/sec CNT0 ;
   278:L P[269] 50mm/sec CNT0 ;
   279:L P[270] 50mm/sec CNT0 ;
   280:L P[271] 50mm/sec CNT0 ;
   281:L P[272] 50mm/sec CNT0 ;
   282:L P[273] 50mm/sec CNT0 ;
   283:L P[274] 50mm/sec CNT0 ;
   284:L P[275] 50mm/sec CNT0 ;
   285:L P[276] 50mm/sec CNT0 ;
   286:L P[277] 50mm/sec CNT0 ;
   287:L P[278] 50mm/sec CNT0 ;
   288:L P[279] 50mm/sec CNT0 ;
   289:L P[280] 50mm/sec CNT0 ;
   290:L P[281] 50mm/sec CNT0 ;
   291:L P[282] 50mm/sec CNT0 ;
   292:L P[283] 50mm/sec CNT0 ;
   293:L P[284] 50mm/sec CNT0 ;
   294:L P[285] 50mm/sec CNT0 ;
   295:L P[286] 50mm/sec CNT0 ;
   296:L P[287] 50mm/sec CNT0 ;
   297:L P[288] 50mm/sec CNT0 ;
   298:L P[289] 50mm/sec CNT0 ;
   299:L P[290] 50mm/sec CNT0 ;
   300:L P[291] 50mm/sec CNT0 ;
   301:L P[292] 100mm/sec CNT0 ;
   302:  !Shape 8 ;
   303:L P[293] 200mm/sec CNT0 ;
   304:L P[294] 100mm/sec CNT0 ;
   305:L P[295] 50mm/sec CNT0 ;
   306:L P[296] 50mm/sec CNT0 ;
   307:L P[297] 50mm/sec CNT0 ;
   308:L P[298] 50mm/sec CNT0 ;
   309:L P[299] 50mm/sec CNT0 ;
   310:L P[300] 50mm/sec CNT0 ;
   311:L P[301] 50mm/sec CNT0 ;
   312:L P[302] 50mm/sec CNT0 ;
   313:L P[303] 50mm/sec CNT0 ;
   314:L P[304] 50mm/sec CNT0 ;
   315:L P[305] 50mm/sec CNT0 ;
   316:L P[306] 50mm/sec CNT0 ;
   317:L P[307] 50mm/sec CNT0 ;
   318:L P[308] 50mm/sec CNT0 ;
   319:L P[309] 50mm/sec CNT0 ;
   320:L P[310] 50mm/sec CNT0 ;
   321:L P[311] 50mm/sec CNT0 ;
   322:L P[312] 50mm/sec CNT0 ;
   323:L P[313] 50mm/sec CNT0 ;
   324:L P[314] 50mm/sec CNT0 ;
   325:L P[315] 50mm/sec CNT0 ;
   326:L P[316] 50mm/sec CNT0 ;
   327:L P[317] 50mm/sec CNT0 ;
   328:L P[318] 50mm/sec CNT0 ;
   329:L P[319] 50mm/sec CNT0 ;
   330:L P[320] 50mm/sec CNT0 ;
   331:L P[321] 50mm/sec CNT0 ;
   332:L P[322] 50mm/sec CNT0 ;
   333:L P[323] 50mm/sec CNT0 ;
   334:L P[324] 50mm/sec CNT0 ;
   335:L P[325] 50mm/sec CNT0 ;
   336:L P[326] 50mm/sec CNT0 ;
   337:L P[327] 50mm/sec CNT0 ;
   338:L P[328] 50mm/sec CNT0 ;
   339:L P[329] 50mm/sec CNT0 ;
   340:L P[330] 50mm/sec CNT0 ;
   341:L P[331] 50mm/sec CNT0 ;
   342:L P[332] 50mm/sec CNT0 ;
   343:L P[333] 50mm/sec CNT0 ;
   344:L P[334] 50mm/sec CNT0 ;
   345:L P[335] 50mm/sec CNT0 ;
   346:L P[336] 50mm/sec CNT0 ;
   347:L P[337] 50mm/sec CNT0 ;
   348:L P[338] 50mm/sec CNT0 ;
   349:L P[339] 50mm/sec CNT0 ;
   350:L P[340] 50mm/sec CNT0 ;
   351:L P[341] 50mm/sec CNT0 ;
   352:L P[342] 50mm/sec CNT0 ;
   353:L P[343] 50mm/sec CNT0 ;
   354:L P[344] 50mm/sec CNT0 ;
   355:L P[345] 50mm/sec CNT0 ;
   356:L P[346] 50mm/sec CNT0 ;
   357:L P[347] 50mm/sec CNT0 ;
   358:L P[348] 50mm/sec CNT0 ;
   359:L P[349] 50mm/sec CNT0 ;
   360:L P[350] 50mm/sec CNT0 ;
   361:L P[351] 50mm/sec CNT0 ;
   362:L P[352] 50mm/sec CNT0 ;
   363:L P[353] 50mm/sec CNT0 ;
   364:L P[354] 50mm/sec CNT0 ;
   365:L P[355] 50mm/sec CNT0 ;
   366:L P[356] 50mm/sec CNT0 ;
   367:L P[357] 50mm/sec CNT0 ;
   368:L P[358] 50mm/sec CNT0 ;
   369:L P[359] 50mm/sec CNT0 ;
   370:L P[360] 50mm/sec CNT0 ;
   371:L P[361] 50mm/sec CNT0 ;
   372:L P[362] 50mm/sec CNT0 ;
   373:L P[363] 50mm/sec CNT0 ;
   374:L P[364] 50mm/sec CNT0 ;
   375:L P[365] 50mm/sec CNT0 ;
   376:L P[366] 50mm/sec CNT0 ;
   377:L P[367] 50mm/sec CNT0 ;
   378:L P[368] 50mm/sec CNT0 ;
   379:L P[369] 50mm/sec CNT0 ;
   380:L P[370] 50mm/sec CNT0 ;
   381:L P[371] 50mm/sec CNT0 ;
   382:L P[372] 50mm/sec CNT0 ;
   383:L P[373] 50mm/sec CNT0 ;
   384:L P[374] 50mm/sec CNT0 ;
   385:L P[375] 50mm/sec CNT0 ;
   386:L P[376] 50mm/sec CNT0 ;
   387:L P[377] 50mm/sec CNT0 ;
   388:L P[378] 50mm/sec CNT0 ;
   389:L P[379] 50mm/sec CNT0 ;
   390:L P[380] 50mm/sec CNT0 ;
   391:L P[381] 50mm/sec CNT0 ;
   392:L P[382] 50mm/sec CNT0 ;
   393:L P[383] 50mm/sec CNT0 ;
   394:L P[384] 50mm/sec CNT0 ;
   395:L P[385] 50mm/sec CNT0 ;
   396:L P[386] 50mm/sec CNT0 ;
   397:L P[387] 50mm/sec CNT0 ;
   398:L P[388] 50mm/sec CNT0 ;
   399:L P[389] 50mm/sec CNT0 ;
   400:L P[390] 50mm/sec CNT0 ;
   401:L P[391] 50mm/sec CNT0 ;
   402:L P[392] 50mm/sec CNT0 ;
   403:L P[393] 50mm/sec CNT0 ;
   404:L P[394] 50mm/sec CNT0 ;
   405:L P[395] 50mm/sec CNT0 ;
   406:L P[396] 50mm/sec CNT0 ;
   407:L P[397] 50mm/sec CNT0 ;
   408:L P[398] 50mm/sec CNT0 ;
   409:L P[399] 50mm/sec CNT0 ;
   410:L P[400] 50mm/sec CNT0 ;
   411:L P[401] 50mm/sec CNT0 ;
   412:L P[402] 50mm/sec CNT0 ;
   413:L P[403] 50mm/sec CNT0 ;
   414:L P[404] 50mm/sec CNT0 ;
   415:L P[405] 50mm/sec CNT0 ;
   416:L P[406] 50mm/sec CNT0 ;
   417:L P[407] 50mm/sec CNT0 ;
   418:L P[408] 50mm/sec CNT0 ;
   419:L P[409] 50mm/sec CNT0 ;
   420:L P[410] 50mm/sec CNT0 ;
   421:L P[411] 50mm/sec CNT0 ;
   422:L P[412] 50mm/sec CNT0 ;
   423:L P[413] 50mm/sec CNT0 ;
   424:L P[414] 50mm/sec CNT0 ;
   425:L P[415] 50mm/sec CNT0 ;
   426:L P[416] 50mm/sec CNT0 ;
   427:L P[417] 50mm/sec CNT0 ;
   428:L P[418] 50mm/sec CNT0 ;
   429:L P[419] 100mm/sec CNT0 ;
   430:  !Shape 9 ;
   431:L P[420] 200mm/sec CNT0 ;
   432:L P[421] 100mm/sec CNT0 ;
   433:L P[422] 50mm/sec CNT0 ;
   434:L P[423] 50mm/sec CNT0 ;
   435:L P[424] 50mm/sec CNT0 ;
   436:L P[425] 50mm/sec CNT0 ;
   437:L P[426] 50mm/sec CNT0 ;
   438:L P[427] 50mm/sec CNT0 ;
   439:L P[428] 50mm/sec CNT0 ;
   440:L P[429] 50mm/sec CNT0 ;
   441:L P[430] 50mm/sec CNT0 ;
   442:L P[431] 50mm/sec CNT0 ;
   443:L P[432] 50mm/sec CNT0 ;
   444:L P[433] 50mm/sec CNT0 ;
   445:L P[434] 50mm/sec CNT0 ;
   446:L P[435] 50mm/sec CNT0 ;
   447:L P[436] 50mm/sec CNT0 ;
   448:L P[437] 50mm/sec CNT0 ;
   449:L P[438] 50mm/sec CNT0 ;
   450:L P[439] 50mm/sec CNT0 ;
   451:L P[440] 50mm/sec CNT0 ;
   452:L P[441] 50mm/sec CNT0 ;
   453:L P[442] 50mm/sec CNT0 ;
   454:L P[443] 50mm/sec CNT0 ;
   455:L P[444] 50mm/sec CNT0 ;
   456:L P[445] 50mm/sec CNT0 ;
   457:L P[446] 50mm/sec CNT0 ;
   458:L P[447] 50mm/sec CNT0 ;
   459:L P[448] 50mm/sec CNT0 ;
   460:L P[449] 50mm/sec CNT0 ;
   461:L P[450] 50mm/sec CNT0 ;
   462:L P[451] 50mm/sec CNT0 ;
   463:L P[452] 50mm/sec CNT0 ;
   464:L P[453] 50mm/sec CNT0 ;
   465:L P[454] 50mm/sec CNT0 ;
   466:L P[455] 50mm/sec CNT0 ;
   467:L P[456] 50mm/sec CNT0 ;
   468:L P[457] 50mm/sec CNT0 ;
   469:L P[458] 50mm/sec CNT0 ;
   470:L P[459] 50mm/sec CNT0 ;
   471:L P[460] 50mm/sec CNT0 ;
   472:L P[461] 50mm/sec CNT0 ;
   473:L P[462] 50mm/sec CNT0 ;
   474:L P[463] 50mm/sec CNT0 ;
   475:L P[464] 50mm/sec CNT0 ;
   476:L P[465] 50mm/sec CNT0 ;
   477:L P[466] 50mm/sec CNT0 ;
   478:L P[467] 50mm/sec CNT0 ;
   479:L P[468] 50mm/sec CNT0 ;
   480:L P[469] 50mm/sec CNT0 ;
   481:L P[470] 50mm/sec CNT0 ;
   482:L P[471] 50mm/sec CNT0 ;
   483:L P[472] 50mm/sec CNT0 ;
   484:L P[473] 50mm/sec CNT0 ;
   485:L P[474] 50mm/sec CNT0 ;
   486:L P[475] 50mm/sec CNT0 ;
   487:L P[476] 50mm/sec CNT0 ;
   488:L P[477] 50mm/sec CNT0 ;
   489:L P[478] 50mm/sec CNT0 ;
   490:L P[479] 50mm/sec CNT0 ;
   491:L P[480] 50mm/sec CNT0 ;
   492:L P[481] 50mm/sec CNT0 ;
   493:L P[482] 50mm/sec CNT0 ;
   494:L P[483] 50mm/sec CNT0 ;
   495:L P[484] 50mm/sec CNT0 ;
   496:L P[485] 50mm/sec CNT0 ;
   497:L P[486] 50mm/sec CNT0 ;
   498:L P[487] 50mm/sec CNT0 ;
   499:L P[488] 50mm/sec CNT0 ;
   500:L P[489] 50mm/sec CNT0 ;
   501:L P[490] 50mm/sec CNT0 ;
   502:L P[491] 50mm/sec CNT0 ;
   503:L P[492] 50mm/sec CNT0 ;
   504:L P[493] 50mm/sec CNT0 ;
   505:L P[494] 50mm/sec CNT0 ;
   506:L P[495] 50mm/sec CNT0 ;
   507:L P[496] 50mm/sec CNT0 ;
   508:L P[497] 50mm/sec CNT0 ;
   509:L P[498] 50mm/sec CNT0 ;
   510:L P[499] 50mm/sec CNT0 ;
   511:L P[500] 50mm/sec CNT0 ;
   512:L P[501] 50mm/sec CNT0 ;
   513:L P[502] 50mm/sec CNT0 ;
   514:L P[503] 50mm/sec CNT0 ;
   515:L P[504] 50mm/sec CNT0 ;
   516:L P[505] 50mm/sec CNT0 ;
   517:L P[506] 50mm/sec CNT0 ;
   518:L P[507] 50mm/sec CNT0 ;
   519:L P[508] 50mm/sec CNT0 ;
   520:L P[509] 50mm/sec CNT0 ;
   521:L P[510] 50mm/sec CNT0 ;
   522:L P[511] 50mm/sec CNT0 ;
   523:L P[512] 50mm/sec CNT0 ;
   524:L P[513] 50mm/sec CNT0 ;
   525:L P[514] 50mm/sec CNT0 ;
   526:L P[515] 50mm/sec CNT0 ;
   527:L P[516] 50mm/sec CNT0 ;
   528:L P[517] 50mm/sec CNT0 ;
   529:L P[518] 50mm/sec CNT0 ;
   530:L P[519] 50mm/sec CNT0 ;
   531:L P[520] 50mm/sec CNT0 ;
   532:L P[521] 50mm/sec CNT0 ;
   533:L P[522] 50mm/sec CNT0 ;
   534:L P[523] 50mm/sec CNT0 ;
   535:L P[524] 50mm/sec CNT0 ;
   536:L P[525] 50mm/sec CNT0 ;
   537:L P[526] 100mm/sec CNT0 ;
   538:J P[1] 200% CNT0 ;
   539:  !End of program ;
/POS
P[1]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.300 mm,	Y = 30.100 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[2]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.300 mm,	Y = 30.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[3]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.000 mm,	Y = 30.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[4]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.600 mm,	Y = 30.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[5]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 19.100 mm,	Y = 30.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[6]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 19.400 mm,	Y = 31.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[7]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 19.500 mm,	Y = 32.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[8]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 19.200 mm,	Y = 33.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[9]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.700 mm,	Y = 33.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[10]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.000 mm,	Y = 34.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[11]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.300 mm,	Y = 34.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[12]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.600 mm,	Y = 33.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[13]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.000 mm,	Y = 33.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[14]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.700 mm,	Y = 32.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[15]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.700 mm,	Y = 31.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[16]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.800 mm,	Y = 31.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[17]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.300 mm,	Y = 30.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[18]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.900 mm,	Y = 30.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[19]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.900 mm,	Y = 30.100 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[20]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.400 mm,	Y = 30.000 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[21]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.400 mm,	Y = 30.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[22]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.600 mm,	Y = 30.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[23]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.000 mm,	Y = 30.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[24]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.800 mm,	Y = 31.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[25]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.700 mm,	Y = 32.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[26]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.800 mm,	Y = 32.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[27]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.100 mm,	Y = 33.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[28]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.700 mm,	Y = 34.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[29]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.400 mm,	Y = 34.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[30]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.200 mm,	Y = 34.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[31]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.800 mm,	Y = 33.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[32]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 19.300 mm,	Y = 33.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[33]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 19.500 mm,	Y = 32.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[34]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 19.400 mm,	Y = 31.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[35]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 19.100 mm,	Y = 30.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[36]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.600 mm,	Y = 30.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[37]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.900 mm,	Y = 30.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[38]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.900 mm,	Y = 30.000 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[39]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.400 mm,	Y = 29.900 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[40]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.400 mm,	Y = 29.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[41]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 61.800 mm,	Y = 32.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[42]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 61.200 mm,	Y = 33.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[43]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 55.300 mm,	Y = 38.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[44]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 55.000 mm,	Y = 39.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[45]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 59.400 mm,	Y = 44.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[46]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 60.000 mm,	Y = 44.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[47]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 61.500 mm,	Y = 46.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[48]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 62.100 mm,	Y = 47.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[49]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.500 mm,	Y = 49.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[50]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.100 mm,	Y = 49.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[51]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.100 mm,	Y = 48.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[52]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.000 mm,	Y = 48.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[53]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.800 mm,	Y = 47.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[54]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.600 mm,	Y = 45.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[55]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.600 mm,	Y = 45.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[56]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.500 mm,	Y = 44.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[57]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.500 mm,	Y = 43.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[58]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.400 mm,	Y = 42.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[59]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.400 mm,	Y = 40.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[60]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.500 mm,	Y = 39.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[61]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.500 mm,	Y = 38.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[62]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.800 mm,	Y = 36.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[63]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.000 mm,	Y = 35.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[64]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.100 mm,	Y = 35.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[65]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.300 mm,	Y = 30.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[66]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.500 mm,	Y = 30.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[67]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.400 mm,	Y = 33.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[68]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.200 mm,	Y = 34.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[69]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.100 mm,	Y = 35.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[70]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.900 mm,	Y = 36.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[71]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.500 mm,	Y = 39.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[72]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.500 mm,	Y = 40.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[73]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.400 mm,	Y = 40.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[74]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.400 mm,	Y = 43.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[75]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.500 mm,	Y = 43.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[76]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.500 mm,	Y = 44.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[77]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.000 mm,	Y = 48.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[78]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.200 mm,	Y = 49.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[79]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.800 mm,	Y = 49.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[80]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.300 mm,	Y = 48.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[81]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 62.800 mm,	Y = 48.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[82]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 61.300 mm,	Y = 46.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[83]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 60.700 mm,	Y = 45.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[84]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 58.300 mm,	Y = 42.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[85]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 57.700 mm,	Y = 42.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[86]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 55.700 mm,	Y = 39.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[87]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 55.300 mm,	Y = 39.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[88]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 55.100 mm,	Y = 38.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[89]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 55.700 mm,	Y = 38.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[90]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.400 mm,	Y = 31.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[91]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.000 mm,	Y = 31.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[92]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.200 mm,	Y = 30.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[93]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.200 mm,	Y = 30.100 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[94]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.700 mm,	Y = 28.800 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[95]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.700 mm,	Y = 28.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[96]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.400 mm,	Y = 28.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[97]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.200 mm,	Y = 28.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[98]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.900 mm,	Y = 29.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[99]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 19.500 mm,	Y = 29.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[100]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.100 mm,	Y = 30.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[101]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.700 mm,	Y = 31.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[102]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.800 mm,	Y = 32.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[103]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.700 mm,	Y = 32.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[104]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.400 mm,	Y = 33.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[105]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.000 mm,	Y = 34.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[106]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 19.500 mm,	Y = 34.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[107]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.900 mm,	Y = 35.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[108]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.200 mm,	Y = 35.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[109]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.400 mm,	Y = 35.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[110]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.600 mm,	Y = 35.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[111]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.000 mm,	Y = 35.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[112]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.400 mm,	Y = 34.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[113]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.900 mm,	Y = 34.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[114]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.500 mm,	Y = 33.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[115]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.300 mm,	Y = 32.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[116]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.300 mm,	Y = 31.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[117]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.500 mm,	Y = 31.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[118]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.800 mm,	Y = 30.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[119]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.200 mm,	Y = 29.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[120]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.700 mm,	Y = 29.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[121]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.300 mm,	Y = 28.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[122]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.300 mm,	Y = 28.900 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[123]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.800 mm,	Y = 28.700 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[124]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.800 mm,	Y = 28.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[125]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.100 mm,	Y = 28.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[126]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.400 mm,	Y = 29.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[127]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.900 mm,	Y = 30.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[128]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.700 mm,	Y = 30.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[129]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.400 mm,	Y = 31.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[130]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.300 mm,	Y = 32.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[131]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.400 mm,	Y = 32.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[132]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.600 mm,	Y = 33.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[133]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.000 mm,	Y = 34.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[134]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.500 mm,	Y = 34.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[135]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.100 mm,	Y = 35.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[136]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.600 mm,	Y = 35.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[137]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.300 mm,	Y = 35.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[138]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 19.100 mm,	Y = 35.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[139]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.200 mm,	Y = 34.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[140]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.500 mm,	Y = 33.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[141]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.700 mm,	Y = 32.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[142]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.800 mm,	Y = 32.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[143]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.700 mm,	Y = 31.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[144]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.100 mm,	Y = 29.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[145]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 19.500 mm,	Y = 29.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[146]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.800 mm,	Y = 28.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[147]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.200 mm,	Y = 28.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[148]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.400 mm,	Y = 28.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[149]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.400 mm,	Y = 28.700 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[150]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 27.100 mm,	Y = 22.100 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[151]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 27.100 mm,	Y = 22.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[152]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 27.800 mm,	Y = 22.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[153]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 29.400 mm,	Y = 22.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[154]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 31.700 mm,	Y = 22.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[155]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 33.800 mm,	Y = 22.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[156]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 36.500 mm,	Y = 24.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[157]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 38.400 mm,	Y = 25.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[158]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 40.900 mm,	Y = 26.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[159]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 43.300 mm,	Y = 28.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[160]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 43.900 mm,	Y = 29.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[161]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 44.500 mm,	Y = 30.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[162]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 46.200 mm,	Y = 31.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[163]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 46.700 mm,	Y = 32.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[164]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 47.200 mm,	Y = 32.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[165]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 47.700 mm,	Y = 33.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[166]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 48.300 mm,	Y = 34.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[167]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 50.800 mm,	Y = 37.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[168]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 51.200 mm,	Y = 37.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[169]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 51.700 mm,	Y = 38.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[170]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 51.400 mm,	Y = 38.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[171]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 50.800 mm,	Y = 39.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[172]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 49.600 mm,	Y = 40.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[173]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 49.000 mm,	Y = 40.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[174]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 48.300 mm,	Y = 41.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[175]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 47.100 mm,	Y = 41.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[176]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 43.300 mm,	Y = 44.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[177]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 38.000 mm,	Y = 47.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[178]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 33.800 mm,	Y = 48.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[179]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 30.000 mm,	Y = 48.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[180]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 28.400 mm,	Y = 48.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[181]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 27.700 mm,	Y = 48.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[182]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 26.900 mm,	Y = 48.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[183]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 26.100 mm,	Y = 48.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[184]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 25.400 mm,	Y = 48.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[185]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 23.900 mm,	Y = 48.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[186]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 19.600 mm,	Y = 47.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[187]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.900 mm,	Y = 45.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[188]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 13.000 mm,	Y = 43.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[189]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 11.100 mm,	Y = 42.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[190]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 10.500 mm,	Y = 41.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[191]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 9.900 mm,	Y = 41.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[192]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 8.700 mm,	Y = 40.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[193]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 7.600 mm,	Y = 39.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[194]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 7.900 mm,	Y = 38.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[195]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 10.900 mm,	Y = 33.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[196]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 11.400 mm,	Y = 32.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[197]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 11.900 mm,	Y = 32.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[198]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 12.300 mm,	Y = 31.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[199]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 13.800 mm,	Y = 29.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[200]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.300 mm,	Y = 29.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[201]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.800 mm,	Y = 28.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[202]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.400 mm,	Y = 28.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[203]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.000 mm,	Y = 27.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[204]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.600 mm,	Y = 27.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[205]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.300 mm,	Y = 25.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[206]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.200 mm,	Y = 24.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[207]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 21.500 mm,	Y = 23.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[208]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 23.600 mm,	Y = 22.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[209]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 25.000 mm,	Y = 22.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[210]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 25.700 mm,	Y = 22.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[211]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 26.400 mm,	Y = 22.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[212]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 26.400 mm,	Y = 22.100 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[213]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 27.200 mm,	Y = 22.000 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[214]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 27.200 mm,	Y = 22.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[215]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 26.400 mm,	Y = 22.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[216]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 25.700 mm,	Y = 22.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[217]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 24.900 mm,	Y = 22.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[218]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 24.200 mm,	Y = 22.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[219]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 23.500 mm,	Y = 22.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[220]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 22.800 mm,	Y = 23.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[221]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.800 mm,	Y = 24.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[222]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.300 mm,	Y = 25.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[223]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.500 mm,	Y = 27.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[224]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.900 mm,	Y = 27.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[225]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.300 mm,	Y = 28.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[226]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.800 mm,	Y = 28.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[227]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.300 mm,	Y = 29.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[228]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 13.700 mm,	Y = 29.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[229]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 12.200 mm,	Y = 31.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[230]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 11.800 mm,	Y = 32.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[231]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 11.300 mm,	Y = 32.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[232]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 10.000 mm,	Y = 34.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[233]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 9.700 mm,	Y = 35.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[234]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 9.200 mm,	Y = 36.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[235]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 7.800 mm,	Y = 38.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[236]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 7.600 mm,	Y = 39.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[237]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 8.000 mm,	Y = 39.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[238]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 8.600 mm,	Y = 40.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[239]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 9.800 mm,	Y = 41.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[240]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 10.400 mm,	Y = 41.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[241]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 11.000 mm,	Y = 42.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[242]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 12.900 mm,	Y = 43.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[243]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 13.500 mm,	Y = 44.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[244]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.200 mm,	Y = 44.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[245]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.800 mm,	Y = 46.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[246]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 19.500 mm,	Y = 47.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[247]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.200 mm,	Y = 47.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[248]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 23.100 mm,	Y = 48.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[249]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 23.800 mm,	Y = 48.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[250]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 24.600 mm,	Y = 48.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[251]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 28.400 mm,	Y = 48.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[252]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 30.000 mm,	Y = 48.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[253]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 30.700 mm,	Y = 48.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[254]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 31.500 mm,	Y = 48.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[255]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 32.300 mm,	Y = 48.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[256]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 33.800 mm,	Y = 48.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[257]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 35.900 mm,	Y = 47.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[258]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 36.600 mm,	Y = 47.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[259]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 37.300 mm,	Y = 47.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[260]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 40.000 mm,	Y = 46.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[261]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 41.300 mm,	Y = 45.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[262]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 42.000 mm,	Y = 45.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[263]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 43.300 mm,	Y = 44.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[264]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 43.900 mm,	Y = 44.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[265]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 44.600 mm,	Y = 43.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[266]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 45.200 mm,	Y = 43.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[267]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 50.200 mm,	Y = 39.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[268]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 50.800 mm,	Y = 39.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[269]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 51.400 mm,	Y = 38.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[270]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 51.900 mm,	Y = 38.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[271]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 50.900 mm,	Y = 37.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[272]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 50.400 mm,	Y = 36.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[273]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 48.500 mm,	Y = 34.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[274]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 47.900 mm,	Y = 33.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[275]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 47.400 mm,	Y = 32.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[276]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 46.300 mm,	Y = 31.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[277]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 45.800 mm,	Y = 31.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[278]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 44.600 mm,	Y = 30.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[279]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 44.000 mm,	Y = 29.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[280]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 43.500 mm,	Y = 29.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[281]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 41.100 mm,	Y = 27.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[282]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 40.500 mm,	Y = 26.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[283]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 39.900 mm,	Y = 26.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[284]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 37.300 mm,	Y = 24.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[285]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 35.400 mm,	Y = 23.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[286]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 34.000 mm,	Y = 23.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[287]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 33.300 mm,	Y = 22.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[288]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 32.600 mm,	Y = 22.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[289]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 31.800 mm,	Y = 22.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[290]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 29.600 mm,	Y = 22.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[291]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 28.000 mm,	Y = 22.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[292]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 28.000 mm,	Y = 22.000 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[293]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 27.700 mm,	Y = 20.400 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[294]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 27.700 mm,	Y = 20.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[295]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 28.400 mm,	Y = 20.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[296]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 29.200 mm,	Y = 20.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[297]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 32.200 mm,	Y = 20.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[298]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 33.700 mm,	Y = 21.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[299]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 34.400 mm,	Y = 21.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[300]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 35.100 mm,	Y = 21.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[301]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 39.000 mm,	Y = 23.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[302]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 41.500 mm,	Y = 25.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[303]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 42.700 mm,	Y = 26.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[304]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 43.300 mm,	Y = 26.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[305]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 43.900 mm,	Y = 27.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[306]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 44.500 mm,	Y = 27.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[307]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 45.100 mm,	Y = 28.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[308]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 48.400 mm,	Y = 31.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[309]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 49.400 mm,	Y = 32.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[310]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 50.000 mm,	Y = 33.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[311]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 51.500 mm,	Y = 35.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[312]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 51.900 mm,	Y = 35.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[313]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 52.400 mm,	Y = 36.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[314]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 52.800 mm,	Y = 37.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[315]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 53.300 mm,	Y = 37.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[316]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 53.800 mm,	Y = 37.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[317]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 55.000 mm,	Y = 36.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[318]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 55.600 mm,	Y = 36.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[319]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 58.000 mm,	Y = 34.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[320]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 58.600 mm,	Y = 34.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[321]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 61.000 mm,	Y = 32.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[322]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 61.600 mm,	Y = 31.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[323]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.400 mm,	Y = 30.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[324]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 63.900 mm,	Y = 29.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[325]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.500 mm,	Y = 29.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[326]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.100 mm,	Y = 28.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[327]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.700 mm,	Y = 27.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[328]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 66.800 mm,	Y = 26.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[329]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 67.300 mm,	Y = 26.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[330]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 68.000 mm,	Y = 25.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[331]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 68.200 mm,	Y = 26.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[332]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 68.000 mm,	Y = 27.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[333]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 67.100 mm,	Y = 29.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[334]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 66.900 mm,	Y = 30.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[335]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 66.600 mm,	Y = 30.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[336]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 66.400 mm,	Y = 31.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[337]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 66.100 mm,	Y = 32.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[338]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.500 mm,	Y = 34.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[339]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.400 mm,	Y = 35.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[340]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.000 mm,	Y = 36.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[341]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.700 mm,	Y = 38.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[342]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.700 mm,	Y = 39.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[343]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.600 mm,	Y = 40.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[344]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.600 mm,	Y = 41.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[345]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.700 mm,	Y = 42.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[346]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.700 mm,	Y = 43.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[347]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.800 mm,	Y = 44.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[348]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.800 mm,	Y = 45.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[349]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.200 mm,	Y = 48.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[350]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.400 mm,	Y = 48.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[351]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.500 mm,	Y = 49.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[352]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.700 mm,	Y = 50.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[353]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.800 mm,	Y = 51.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[354]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 66.200 mm,	Y = 52.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[355]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.700 mm,	Y = 53.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[356]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.100 mm,	Y = 52.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[357]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.600 mm,	Y = 52.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[358]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 62.600 mm,	Y = 49.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[359]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 62.000 mm,	Y = 49.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[360]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 60.100 mm,	Y = 47.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[361]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 59.500 mm,	Y = 46.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[362]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 57.000 mm,	Y = 43.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[363]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 56.400 mm,	Y = 42.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[364]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 54.500 mm,	Y = 40.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[365]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 53.900 mm,	Y = 39.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[366]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 53.300 mm,	Y = 39.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[367]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 52.100 mm,	Y = 40.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[368]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 51.500 mm,	Y = 40.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[369]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 49.600 mm,	Y = 42.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[370]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 49.000 mm,	Y = 42.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[371]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 43.300 mm,	Y = 46.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[372]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 42.600 mm,	Y = 46.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[373]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 42.000 mm,	Y = 46.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[374]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 40.700 mm,	Y = 47.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[375]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 40.000 mm,	Y = 47.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[376]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 38.000 mm,	Y = 48.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[377]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 37.300 mm,	Y = 49.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[378]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 36.600 mm,	Y = 49.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[379]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 33.700 mm,	Y = 50.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[380]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 30.700 mm,	Y = 50.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[381]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 27.500 mm,	Y = 50.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[382]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 25.200 mm,	Y = 50.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[383]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 24.500 mm,	Y = 50.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[384]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 23.800 mm,	Y = 49.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[385]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 23.000 mm,	Y = 49.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[386]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 22.300 mm,	Y = 49.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[387]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 19.400 mm,	Y = 48.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[388]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.300 mm,	Y = 47.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[389]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 16.700 mm,	Y = 47.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[390]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.700 mm,	Y = 46.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[391]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.000 mm,	Y = 46.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[392]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 10.900 mm,	Y = 44.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[393]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 10.300 mm,	Y = 43.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[394]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 9.600 mm,	Y = 43.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[395]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 6.700 mm,	Y = 40.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[396]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 6.100 mm,	Y = 40.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[397]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 5.600 mm,	Y = 39.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[398]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 8.000 mm,	Y = 35.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[399]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 8.400 mm,	Y = 34.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[400]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 8.700 mm,	Y = 33.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[401]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 10.000 mm,	Y = 32.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[402]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 10.500 mm,	Y = 31.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[403]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 10.900 mm,	Y = 30.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[404]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 11.400 mm,	Y = 30.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[405]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 11.900 mm,	Y = 29.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[406]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 12.400 mm,	Y = 29.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[407]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 12.900 mm,	Y = 28.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[408]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 13.500 mm,	Y = 27.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[409]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.000 mm,	Y = 27.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[410]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.600 mm,	Y = 26.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[411]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.100 mm,	Y = 26.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[412]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.500 mm,	Y = 24.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[413]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.100 mm,	Y = 22.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[414]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 22.100 mm,	Y = 21.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[415]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 24.200 mm,	Y = 20.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[416]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 24.900 mm,	Y = 20.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[417]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 25.600 mm,	Y = 20.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[418]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 27.100 mm,	Y = 20.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[419]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 27.100 mm,	Y = 20.400 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[420]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 27.800 mm,	Y = 20.300 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[421]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 27.800 mm,	Y = 20.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[422]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 25.500 mm,	Y = 20.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[423]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 22.600 mm,	Y = 21.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[424]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 20.600 mm,	Y = 22.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[425]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.400 mm,	Y = 24.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[426]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 15.000 mm,	Y = 26.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[427]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 14.400 mm,	Y = 26.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[428]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 13.800 mm,	Y = 27.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[429]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 13.400 mm,	Y = 27.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[430]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 12.800 mm,	Y = 28.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[431]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 10.800 mm,	Y = 30.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[432]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 10.400 mm,	Y = 31.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[433]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 9.900 mm,	Y = 32.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[434]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 7.100 mm,	Y = 36.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[435]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 5.800 mm,	Y = 39.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[436]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 5.600 mm,	Y = 39.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[437]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 6.100 mm,	Y = 40.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[438]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 6.700 mm,	Y = 40.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[439]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 7.200 mm,	Y = 41.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[440]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 9.000 mm,	Y = 42.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[441]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 9.700 mm,	Y = 43.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[442]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 10.300 mm,	Y = 43.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[443]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 13.400 mm,	Y = 46.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[444]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 17.400 mm,	Y = 48.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[445]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 18.800 mm,	Y = 48.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[446]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 19.400 mm,	Y = 48.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[447]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 22.300 mm,	Y = 49.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[448]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 23.000 mm,	Y = 49.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[449]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 23.800 mm,	Y = 49.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[450]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 24.500 mm,	Y = 50.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[451]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 25.200 mm,	Y = 50.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[452]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 27.500 mm,	Y = 50.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[453]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 30.700 mm,	Y = 50.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[454]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 33.800 mm,	Y = 50.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[455]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 36.600 mm,	Y = 49.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[456]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 37.300 mm,	Y = 49.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[457]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 38.000 mm,	Y = 48.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[458]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 40.700 mm,	Y = 47.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[459]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 45.900 mm,	Y = 44.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[460]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 50.900 mm,	Y = 41.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[461]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 51.500 mm,	Y = 40.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[462]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 53.400 mm,	Y = 39.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[463]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 54.500 mm,	Y = 40.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[464]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 56.400 mm,	Y = 42.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[465]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 57.000 mm,	Y = 43.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[466]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 59.500 mm,	Y = 46.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[467]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 60.000 mm,	Y = 47.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[468]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 62.000 mm,	Y = 49.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[469]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 62.600 mm,	Y = 50.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[470]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.600 mm,	Y = 52.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[471]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.100 mm,	Y = 52.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[472]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.700 mm,	Y = 53.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[473]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 66.200 mm,	Y = 52.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[474]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.800 mm,	Y = 51.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[475]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.700 mm,	Y = 50.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[476]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.500 mm,	Y = 49.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[477]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.300 mm,	Y = 48.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[478]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.100 mm,	Y = 47.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[479]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.800 mm,	Y = 45.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[480]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.800 mm,	Y = 44.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[481]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.700 mm,	Y = 43.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[482]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.700 mm,	Y = 42.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[483]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.600 mm,	Y = 42.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[484]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.600 mm,	Y = 40.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[485]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.700 mm,	Y = 39.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[486]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.700 mm,	Y = 38.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[487]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.000 mm,	Y = 36.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[488]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.200 mm,	Y = 35.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[489]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.300 mm,	Y = 35.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[490]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 66.100 mm,	Y = 32.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[491]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 66.400 mm,	Y = 31.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[492]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 66.600 mm,	Y = 30.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[493]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 66.900 mm,	Y = 30.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[494]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 67.100 mm,	Y = 29.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[495]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 67.700 mm,	Y = 28.000 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[496]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 68.200 mm,	Y = 26.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[497]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 68.100 mm,	Y = 25.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[498]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 67.500 mm,	Y = 26.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[499]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 67.000 mm,	Y = 26.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[500]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 65.300 mm,	Y = 28.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[501]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.700 mm,	Y = 28.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[502]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 64.100 mm,	Y = 29.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[503]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 62.300 mm,	Y = 30.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[504]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 61.800 mm,	Y = 31.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[505]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 56.400 mm,	Y = 35.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[506]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 55.800 mm,	Y = 36.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[507]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 54.600 mm,	Y = 37.200 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[508]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 54.000 mm,	Y = 37.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[509]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 53.400 mm,	Y = 37.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[510]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 53.000 mm,	Y = 37.100 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[511]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 52.500 mm,	Y = 36.500 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[512]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 52.100 mm,	Y = 35.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[513]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 48.600 mm,	Y = 31.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[514]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 45.200 mm,	Y = 28.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[515]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 44.600 mm,	Y = 27.800 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[516]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 44.100 mm,	Y = 27.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[517]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 42.900 mm,	Y = 26.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[518]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 42.300 mm,	Y = 25.900 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[519]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 41.700 mm,	Y = 25.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[520]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 39.200 mm,	Y = 23.700 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[521]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 36.600 mm,	Y = 22.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[522]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 34.500 mm,	Y = 21.400 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[523]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 31.700 mm,	Y = 20.600 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[524]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 29.400 mm,	Y = 20.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[525]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 28.600 mm,	Y = 20.300 mm,	Z = 0.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
P[526]{
	GP1:
	 UF : 4, UT : 9,	CONFIG : 'F U T, 0, 0, 0',
	 X = 28.600 mm,	Y = 20.300 mm,	Z = 10.000 mm,
	 W = 59.855 deg,	P = -83.452 deg,	R = -153.620 deg
};
/END
